name: Blob storage website CI

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
      
    - name: Build website
      run: |
        npm install
        npm run build

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name kowmalgallery --auth-mode key -d '$web' -s ./out
    # - name: Purge CDN endpoint
    #   uses: azure/CLI@v1
    #   with:
    #     inlineScript: |
    #        az cdn endpoint purge --content-paths  "/*" --profile-name "CDN_PROFILE_NAME" --name "CDN_ENDPOINT" --resource-group "RESOURCE_GROUP"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
